language: ruby
rvm:
- 2.6
before_install:
  - gem install ruby_dep
  - gem install github-pages
  - gem install octopress-escape-code
branches:
  only:
    - master
    - develop
script: "jekyll build"

